before:
  hooks:
  - make dep

builds:
  - binary: freeport
    main: ./cmd/freeport
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -a -installsuffix cgo
      - -X main.gitTag={{.Tag}} -X main.gitCommit={{.Commit}} -X main.gitBranch={{.Branch}}

archives:
  - builds: [freeport]

changelog:
  sort: asc

nfpms:
  - vendor: freeport
    homepage: https://github.com/artemshalin/freeport
    maintainer: Artem Shalin
    description: Command-line utility that gets an unoccupied port and prints it to stdout.
    license: MIT
    formats: [ deb, rpm ]